### ISSUE TITLE
4. Timsheet days and hours to current month end by default

### ISSUE THREAD

**Issue by SeneTeam** [SeneTeam/ecom-admin-2-#4]
Add values of hours and codes to cells to the end of current month instead of today()

![image](https://user-images.githubusercontent.com/87410617/168422608-6a99faa7-f029-45d6-95f9-52799b6c44b3.png)

WAIT WITH THIS ISSUE. I have to double check with our customer

**Comment by SeneTeam** [comment]
It should add values until endDate or if endDate is null untill there are any month in timesheet

**Comment by elisealcala** [comment]
@Seniorcorder I think we will have a performance issue for this, what I can do is to complete the current year with the hours.

**Comment by SeneTeam** [comment]
Could you make rolling 12 month instead? Because if it is current year and you are in december so you woould not be able to see hours of next month (january 2023)

**Comment by SeneTeam** [comment]
no. add 12 month to current month
