### ISSUE TITLE
make all overflows in application the same as in example

### ISSUE THREAD

**Issue by SeneTeam** [SeneTeam/ecom-admin-2-#6]
![image](https://user-images.githubusercontent.com/87410617/168507353-9504ba31-fa68-401c-a491-1c00c02929da.png)

**Comment by SeneTeam** [comment]
I mean that every overflow (both x and y) should look the same in application/ pages. Because now timesheet has one style and modals other.
I prefer to have overflow as in picture above

**Comment by elisealcala** [comment]
@Seniorcorder how can I see the modal scroll bar?

**Comment by SeneTeam** [comment]
![image](https://user-images.githubusercontent.com/87410617/168620352-0967d8be-f1ea-44f4-b421-6e155bc9016f.png)

**Comment by SeneTeam** [comment]
![image](https://user-images.githubusercontent.com/87410617/168623695-ac32aa3b-925c-4bb4-bb78-bb1524cedfe7.png)

**Comment by SeneTeam** [comment]
Hello. can you check all the pages?

![image](https://user-images.githubusercontent.com/87410617/168711996-0d4f0546-1202-40e0-b47b-8679f872bc77.png)

**Comment by SeneTeam** [comment]
Not on sidebar. But on Pages. I mean where I see list of employees or page of employee details

**Comment by elisealcala** [comment]
@Seniorcorder I think this is a chrome issue, I can't see the scrollbar either.

**Comment by SeneTeam** [comment]
What do you mean? I don't think it's a chrome issue. I think, it's possible to add a scroll bar. Can you recheck it?

**Comment by elisealcala** [comment]
I review it, and there are some css classes that hides the scroll, can you check that please? there is a .main-content class and a .bg class.

**Comment by SeneTeam** [comment]
so, can't make the scroll bar on that?

**Comment by elisealcala** [comment]
I need to update those classes

**Comment by elisealcala** [comment]
@Seniorcorder I fixed the scrollbar for this

**Comment by SeneTeam** [comment]
I can see some strange section.

![image](https://user-images.githubusercontent.com/87410617/168882938-56a1a51a-e686-4b2c-aa34-b3c72f531e0b.png)

**Comment by elisealcala** [comment]
@Seniorcorder I pushed a fix
