### ISSUE TITLE
Timesheet page

### ISSUE THREAD

**Issue by SeneTeam** [SeneTeam/ecom-admin-2-#7]
1. Hours and action codes should stop on endDate otherwise (if endDate is null or empty) as described earlier = current month + 12 next month
2. Timeline row should not have drag functionality. Add this icon instead as in figma:
![image](https://user-images.githubusercontent.com/87410617/168670277-23034e0f-bfb3-4525-adfc-597cef391e99.png)

3. Timeline row is not starting and finishing on the edges of spot:
![image](https://user-images.githubusercontent.com/87410617/168670381-91300565-4200-4856-83cb-10bb7d74aeae.png)

**Comment by elisealcala** [comment]
`Hours and action codes should stop on endDate otherwise (if endDate is null or empty) as described earlier = current month + 12 next month`

endDate of what? of the workaction?

**Comment by SeneTeam** [comment]
no no. endDate of employment:

**Comment by SeneTeam** [comment]
![image](https://user-images.githubusercontent.com/87410617/168856026-11c7fa9a-a3fe-41f7-bcdb-294a73d792e1.png)

**Comment by elisealcala** [comment]
@Seniorcorder I pushed my changes for this

**Comment by SeneTeam** [comment]
is there any easy way to de-activate select and drag functionality for timeline?

**Comment by elisealcala** [comment]
@Seniorcorder fixed
